# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 644)
        MainWindow.setMinimumSize(QtCore.QSize(1037, 0))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(66, 93, 107);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(20, 0))
        self.frame.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.framePushButtons = QtWidgets.QFrame(self.frame)
        self.framePushButtons.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.framePushButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePushButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePushButtons.setObjectName("framePushButtons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.framePushButtons)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameTempMain = QtWidgets.QFrame(self.framePushButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.frameTempMain.sizePolicy().hasHeightForWidth())
        self.frameTempMain.setSizePolicy(sizePolicy)
        self.frameTempMain.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameTempMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTempMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTempMain.setObjectName("frameTempMain")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frameTempMain)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frameLineTemp = QtWidgets.QFrame(self.frameTempMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.frameLineTemp.sizePolicy().hasHeightForWidth())
        self.frameLineTemp.setSizePolicy(sizePolicy)
        self.frameLineTemp.setMinimumSize(QtCore.QSize(20, 50))
        self.frameLineTemp.setMaximumSize(QtCore.QSize(20, 50))
        self.frameLineTemp.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameLineTemp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineTemp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLineTemp.setObjectName("frameLineTemp")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frameLineTemp)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.labelLineTemp = QtWidgets.QLabel(self.frameLineTemp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLineTemp.sizePolicy().hasHeightForWidth())
        self.labelLineTemp.setSizePolicy(sizePolicy)
        self.labelLineTemp.setMinimumSize(QtCore.QSize(20, 50))
        self.labelLineTemp.setMaximumSize(QtCore.QSize(20, 50))
        self.labelLineTemp.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.labelLineTemp.setText("")
        self.labelLineTemp.setPixmap(QtGui.QPixmap(":/icons/line.svg"))
        self.labelLineTemp.setScaledContents(True)
        self.labelLineTemp.setObjectName("labelLineTemp")
        self.horizontalLayout_27.addWidget(self.labelLineTemp)
        self.horizontalLayout_26.addWidget(self.frameLineTemp)
        self.frameTemp = QtWidgets.QFrame(self.frameTempMain)
        self.frameTemp.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameTemp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTemp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTemp.setObjectName("frameTemp")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frameTemp)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButtonTemp = QtWidgets.QPushButton(self.frameTemp)
        self.pushButtonTemp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTemp.sizePolicy().hasHeightForWidth())
        self.pushButtonTemp.setSizePolicy(sizePolicy)
        self.pushButtonTemp.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonTemp.setStyleSheet("QPushButton {\n"
"    background-color: rgb(25, 27, 33);\n"
"    border: 0px;\n"
"    border-image: url(:/icons/temp_ser.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(25, 27, 33);\n"
"    border: 0px;\n"
"    border-image: url(:/icons/temp_white.svg);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButtonTemp.setText("")
        self.pushButtonTemp.setIconSize(QtCore.QSize(35, 50))
        self.pushButtonTemp.setCheckable(False)
        self.pushButtonTemp.setChecked(False)
        self.pushButtonTemp.setObjectName("pushButtonTemp")
        self.horizontalLayout_28.addWidget(self.pushButtonTemp)
        self.horizontalLayout_26.addWidget(self.frameTemp)
        self.verticalLayout_3.addWidget(self.frameTempMain)
        self.framePressureMain = QtWidgets.QFrame(self.framePushButtons)
        self.framePressureMain.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.framePressureMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePressureMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePressureMain.setObjectName("framePressureMain")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.framePressureMain)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frameLinePressure = QtWidgets.QFrame(self.framePressureMain)
        self.frameLinePressure.setMinimumSize(QtCore.QSize(20, 50))
        self.frameLinePressure.setMaximumSize(QtCore.QSize(20, 50))
        self.frameLinePressure.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameLinePressure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLinePressure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLinePressure.setObjectName("frameLinePressure")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frameLinePressure)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.labeLinePressure = QtWidgets.QLabel(self.frameLinePressure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labeLinePressure.sizePolicy().hasHeightForWidth())
        self.labeLinePressure.setSizePolicy(sizePolicy)
        self.labeLinePressure.setMinimumSize(QtCore.QSize(20, 50))
        self.labeLinePressure.setMaximumSize(QtCore.QSize(20, 50))
        self.labeLinePressure.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.labeLinePressure.setText("")
        self.labeLinePressure.setPixmap(QtGui.QPixmap(":/icons/line.svg"))
        self.labeLinePressure.setScaledContents(True)
        self.labeLinePressure.setObjectName("labeLinePressure")
        self.horizontalLayout_33.addWidget(self.labeLinePressure)
        self.horizontalLayout_32.addWidget(self.frameLinePressure)
        self.framePressure = QtWidgets.QFrame(self.framePressureMain)
        self.framePressure.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.framePressure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePressure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePressure.setObjectName("framePressure")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.framePressure)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButtonPressure = QtWidgets.QPushButton(self.framePressure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPressure.sizePolicy().hasHeightForWidth())
        self.pushButtonPressure.setSizePolicy(sizePolicy)
        self.pushButtonPressure.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonPressure.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(25, 27, 33);\n"
"    border-image: url(:/icons/pressure-ser.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(25, 27, 33);\n"
"    border-image: url(:/icons/pressure-white.svg);\n"
"\n"
"}")
        self.pushButtonPressure.setText("")
        self.pushButtonPressure.setObjectName("pushButtonPressure")
        self.horizontalLayout_34.addWidget(self.pushButtonPressure)
        self.horizontalLayout_32.addWidget(self.framePressure)
        self.verticalLayout_3.addWidget(self.framePressureMain)
        self.frameIlluminationMain = QtWidgets.QFrame(self.framePushButtons)
        self.frameIlluminationMain.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameIlluminationMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIlluminationMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIlluminationMain.setObjectName("frameIlluminationMain")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frameIlluminationMain)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frameLineIllumination = QtWidgets.QFrame(self.frameIlluminationMain)
        self.frameLineIllumination.setMinimumSize(QtCore.QSize(20, 50))
        self.frameLineIllumination.setMaximumSize(QtCore.QSize(20, 50))
        self.frameLineIllumination.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameLineIllumination.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineIllumination.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLineIllumination.setObjectName("frameLineIllumination")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frameLineIllumination)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.labelLineIlluminattion = QtWidgets.QLabel(self.frameLineIllumination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.labelLineIlluminattion.sizePolicy().hasHeightForWidth())
        self.labelLineIlluminattion.setSizePolicy(sizePolicy)
        self.labelLineIlluminattion.setMinimumSize(QtCore.QSize(20, 50))
        self.labelLineIlluminattion.setMaximumSize(QtCore.QSize(20, 50))
        self.labelLineIlluminattion.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.labelLineIlluminattion.setText("")
        self.labelLineIlluminattion.setPixmap(QtGui.QPixmap(":/icons/line.svg"))
        self.labelLineIlluminattion.setScaledContents(True)
        self.labelLineIlluminattion.setObjectName("labelLineIlluminattion")
        self.horizontalLayout_30.addWidget(self.labelLineIlluminattion)
        self.horizontalLayout_29.addWidget(self.frameLineIllumination)
        self.frameIllumination = QtWidgets.QFrame(self.frameIlluminationMain)
        self.frameIllumination.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameIllumination.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIllumination.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIllumination.setObjectName("frameIllumination")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frameIllumination)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.pushButtonIllumination = QtWidgets.QPushButton(self.frameIllumination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonIllumination.sizePolicy().hasHeightForWidth())
        self.pushButtonIllumination.setSizePolicy(sizePolicy)
        self.pushButtonIllumination.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonIllumination.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(25, 27, 33);\n"
"    \n"
"    border-image: url(:/icons/light-ser.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(25, 27, 33);\n"
"    border-image: url(:/icons/light-white.svg);\n"
"\n"
"}")
        self.pushButtonIllumination.setText("")
        self.pushButtonIllumination.setObjectName("pushButtonIllumination")
        self.horizontalLayout_31.addWidget(self.pushButtonIllumination)
        self.horizontalLayout_29.addWidget(self.frameIllumination)
        self.verticalLayout_3.addWidget(self.frameIlluminationMain)
        self.frameAccelerationMain = QtWidgets.QFrame(self.framePushButtons)
        self.frameAccelerationMain.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameAccelerationMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAccelerationMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAccelerationMain.setObjectName("frameAccelerationMain")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frameAccelerationMain)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.frameLineAcceleration = QtWidgets.QFrame(self.frameAccelerationMain)
        self.frameLineAcceleration.setMinimumSize(QtCore.QSize(20, 50))
        self.frameLineAcceleration.setMaximumSize(QtCore.QSize(20, 50))
        self.frameLineAcceleration.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameLineAcceleration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineAcceleration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLineAcceleration.setObjectName("frameLineAcceleration")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frameLineAcceleration)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.labelLineAcceleration = QtWidgets.QLabel(self.frameLineAcceleration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLineAcceleration.sizePolicy().hasHeightForWidth())
        self.labelLineAcceleration.setSizePolicy(sizePolicy)
        self.labelLineAcceleration.setMinimumSize(QtCore.QSize(20, 50))
        self.labelLineAcceleration.setMaximumSize(QtCore.QSize(20, 50))
        self.labelLineAcceleration.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.labelLineAcceleration.setText("")
        self.labelLineAcceleration.setPixmap(QtGui.QPixmap(":/icons/line.svg"))
        self.labelLineAcceleration.setScaledContents(True)
        self.labelLineAcceleration.setObjectName("labelLineAcceleration")
        self.horizontalLayout_36.addWidget(self.labelLineAcceleration)
        self.horizontalLayout_35.addWidget(self.frameLineAcceleration)
        self.frameAcceleration = QtWidgets.QFrame(self.frameAccelerationMain)
        self.frameAcceleration.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 0px\n"
"")
        self.frameAcceleration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAcceleration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAcceleration.setObjectName("frameAcceleration")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frameAcceleration)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButtonAcceleration = QtWidgets.QPushButton(self.frameAcceleration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAcceleration.sizePolicy().hasHeightForWidth())
        self.pushButtonAcceleration.setSizePolicy(sizePolicy)
        self.pushButtonAcceleration.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonAcceleration.setStyleSheet("QPushButton {\n"
"background-color: rgb(25, 27, 33);\n"
"\n"
"    border-image: url(:/icons/movement-sensor-ser.svg);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(25, 27, 33);\n"
"    border-image: url(:/icons/movement-sensor-white.svg);\n"
"\n"
"}\n"
"")
        self.pushButtonAcceleration.setText("")
        self.pushButtonAcceleration.setObjectName("pushButtonAcceleration")
        self.horizontalLayout_37.addWidget(self.pushButtonAcceleration)
        self.horizontalLayout_35.addWidget(self.frameAcceleration)
        self.verticalLayout_3.addWidget(self.frameAccelerationMain)
        self.verticalLayout.addWidget(self.framePushButtons, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(860, 620))
        self.stackedWidget.setStyleSheet("background-color: rgb(41, 43, 51);\n"
"border: 1px;\n"
"border-radius: 20px")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(41, 43, 51);\n"
"border: 1px;\n"
"border-radius: 20px")
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.pageTemperature = QtWidgets.QWidget()
        self.pageTemperature.setStyleSheet("background-color: rgb(41, 43, 51);\n"
"border: 1px;\n"
"border-radius: 20px")
        self.pageTemperature.setObjectName("pageTemperature")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageTemperature)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameLabelTemperature = QtWidgets.QFrame(self.pageTemperature)
        self.frameLabelTemperature.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameLabelTemperature.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLabelTemperature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelTemperature.setObjectName("frameLabelTemperature")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameLabelTemperature)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelTemperature = QtWidgets.QLabel(self.frameLabelTemperature)
        self.labelTemperature.setStyleSheet("background-color: rgb(31, 33, 41);\n"
"border: 0px")
        self.labelTemperature.setObjectName("labelTemperature")
        self.verticalLayout_5.addWidget(self.labelTemperature, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.frameLabelTemperature)
        self.frameGraphTemperature = QtWidgets.QFrame(self.pageTemperature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGraphTemperature.sizePolicy().hasHeightForWidth())
        self.frameGraphTemperature.setSizePolicy(sizePolicy)
        self.frameGraphTemperature.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameGraphTemperature.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphTemperature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphTemperature.setObjectName("frameGraphTemperature")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frameGraphTemperature)
        self.verticalLayout_12.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_12.setSpacing(8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.graphicsViewTemp = QtWidgets.QWidget(self.frameGraphTemperature)
        self.graphicsViewTemp.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.graphicsViewTemp.setObjectName("graphicsViewTemp")
        self.verticalLayout_12.addWidget(self.graphicsViewTemp)
        self.verticalLayout_4.addWidget(self.frameGraphTemperature)
        self.stackedWidget.addWidget(self.pageTemperature)
        self.pagePressure = QtWidgets.QWidget()
        self.pagePressure.setStyleSheet("background-color: rgb(41, 43, 51);\n"
"border: 1px;\n"
"border-radius: 20px")
        self.pagePressure.setObjectName("pagePressure")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pagePressure)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frameLabelPressure = QtWidgets.QFrame(self.pagePressure)
        self.frameLabelPressure.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameLabelPressure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLabelPressure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelPressure.setObjectName("frameLabelPressure")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameLabelPressure)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelPressure = QtWidgets.QLabel(self.frameLabelPressure)
        self.labelPressure.setStyleSheet("background-color: rgb(31, 33, 41);\n"
"border: 0px")
        self.labelPressure.setObjectName("labelPressure")
        self.verticalLayout_6.addWidget(self.labelPressure, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_7.addWidget(self.frameLabelPressure)
        self.frameGraphPressure = QtWidgets.QFrame(self.pagePressure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGraphPressure.sizePolicy().hasHeightForWidth())
        self.frameGraphPressure.setSizePolicy(sizePolicy)
        self.frameGraphPressure.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameGraphPressure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphPressure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphPressure.setObjectName("frameGraphPressure")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frameGraphPressure)
        self.verticalLayout_13.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_13.setSpacing(8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.graphicsViewPressure = QtWidgets.QWidget(self.frameGraphPressure)
        self.graphicsViewPressure.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.graphicsViewPressure.setObjectName("graphicsViewPressure")
        self.verticalLayout_13.addWidget(self.graphicsViewPressure)
        self.verticalLayout_7.addWidget(self.frameGraphPressure)
        self.stackedWidget.addWidget(self.pagePressure)
        self.pageIllumination = QtWidgets.QWidget()
        self.pageIllumination.setStyleSheet("background-color: rgb(41, 43, 51);\n"
"border: 1px;\n"
"border-radius: 20px")
        self.pageIllumination.setObjectName("pageIllumination")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageIllumination)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frameLabelIllumination = QtWidgets.QFrame(self.pageIllumination)
        self.frameLabelIllumination.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameLabelIllumination.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLabelIllumination.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelIllumination.setObjectName("frameLabelIllumination")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameLabelIllumination)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelIllumination = QtWidgets.QLabel(self.frameLabelIllumination)
        self.labelIllumination.setStyleSheet("background-color: rgb(31, 33, 41);\n"
"border: 0px")
        self.labelIllumination.setObjectName("labelIllumination")
        self.verticalLayout_8.addWidget(self.labelIllumination, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frameLabelIllumination)
        self.frameGraphIllumination = QtWidgets.QFrame(self.pageIllumination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGraphIllumination.sizePolicy().hasHeightForWidth())
        self.frameGraphIllumination.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.frameGraphIllumination.setFont(font)
        self.frameGraphIllumination.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameGraphIllumination.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphIllumination.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphIllumination.setObjectName("frameGraphIllumination")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGraphIllumination)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsViewIllunination = QtWidgets.QWidget(self.frameGraphIllumination)
        self.graphicsViewIllunination.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.graphicsViewIllunination.setObjectName("graphicsViewIllunination")
        self.verticalLayout_2.addWidget(self.graphicsViewIllunination)
        self.verticalLayout_9.addWidget(self.frameGraphIllumination)
        self.stackedWidget.addWidget(self.pageIllumination)
        self.pageAcceleration = QtWidgets.QWidget()
        self.pageAcceleration.setStyleSheet("background-color: rgb(41, 43, 51);\n"
"border: 1px;\n"
"border-radius: 20px")
        self.pageAcceleration.setObjectName("pageAcceleration")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageAcceleration)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frameLabelAcceleration = QtWidgets.QFrame(self.pageAcceleration)
        self.frameLabelAcceleration.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameLabelAcceleration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLabelAcceleration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLabelAcceleration.setObjectName("frameLabelAcceleration")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameLabelAcceleration)
        self.verticalLayout_10.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelAcceleration = QtWidgets.QLabel(self.frameLabelAcceleration)
        self.labelAcceleration.setStyleSheet("background-color: rgb(31, 33, 41);\n"
"border: 0px")
        self.labelAcceleration.setObjectName("labelAcceleration")
        self.verticalLayout_10.addWidget(self.labelAcceleration, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_11.addWidget(self.frameLabelAcceleration)
        self.frameGraphAcceleration = QtWidgets.QFrame(self.pageAcceleration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGraphAcceleration.sizePolicy().hasHeightForWidth())
        self.frameGraphAcceleration.setSizePolicy(sizePolicy)
        self.frameGraphAcceleration.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.frameGraphAcceleration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphAcceleration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphAcceleration.setObjectName("frameGraphAcceleration")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frameGraphAcceleration)
        self.verticalLayout_15.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_15.setSpacing(8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.graphicsViewAcceleration = QtWidgets.QWidget(self.frameGraphAcceleration)
        self.graphicsViewAcceleration.setStyleSheet("background-color: rgb(25, 27, 33);\n"
"border: 1px; \n"
"border-radius: 20px")
        self.graphicsViewAcceleration.setObjectName("graphicsViewAcceleration")
        self.verticalLayout_15.addWidget(self.graphicsViewAcceleration)
        self.verticalLayout_11.addWidget(self.frameGraphAcceleration)
        self.stackedWidget.addWidget(self.pageAcceleration)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonTemp.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Температура</span></p></body></html>"))
        self.pushButtonPressure.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Давление</span></p></body></html>"))
        self.pushButtonPressure.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButtonIllumination.setToolTip(_translate("MainWindow", "<html><head/><body><p>Освещенность</p></body></html>"))
        self.pushButtonAcceleration.setToolTip(_translate("MainWindow", "<html><head/><body><p>Акселерометр</p></body></html>"))
        self.labelTemperature.setText(_translate("MainWindow", "Температура"))
        self.labelPressure.setText(_translate("MainWindow", " Давление"))
        self.labelIllumination.setText(_translate("MainWindow", "Освещенность"))
        self.labelAcceleration.setText(_translate("MainWindow", "Акселерометр"))



